server:
  port: 9091
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/learneasy
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#docker run -d -p "27017:27017" mongo